const keys = {
    REACT_APP_OPENAI_API_KEY: "BLAH",
    REACT_APP_OPENAI_URL: "BLAH",
    REACT_APP_RECAPTCHA_SITE_KEY: "BLAH",
    REACT_APP_RECAPTCHA_SECRET_KEY: "BLAH",
    REACT_APP_FIREBASE_API_KEY: "BLAH",
    REACT_APP_STRIPE_PUBLIC_KEY: "BLAH",
    REACT_APP_STRIPE_SECRET_KEY: "BLAH",
    REACT_APP_STRIPE_SIGNING_SECRET: "BLAH"
}

export default keys